blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    
    path('', views.blog, name='blog')
]

ferdistory4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('matkul/', include('matkul.urls')),
    path('kegiatan/', include('kegiatan.urls')),
]

kegiatan/urls.py
from django.urls import path
from django.conf.urls import url

from .views import  create_kegiatan, register_kegiatan, list_kegiatan, list_peserta

app_name = 'kegiatan'

urlpatterns = [
    
    path('create_kegiatan', create_kegiatan, name='create_kegiatan'),
    path('register_kegiatan/<id>', register_kegiatan, name='register_kegiatan'),
    path('list_peserta/<id>', list_peserta, name='list_peserta'),
    path('list_kegiatan', list_kegiatan, name='list_kegiatan'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    
    path('', views.home, name='home'),
   
]

matkul/urls.py
from django.urls import path
from django.conf.urls import url

from .views import  create_matkul, list_matkul, detail_matkul, delete_matkul

app_name = 'matkul'

urlpatterns = [
    
    path('create_matkul', create_matkul, name='create_matkul'),
    path('list_matkul', list_matkul, name='list_matkul'),
    path('<id>', detail_matkul ),
    path('<id>/delete', delete_matkul ),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
    <!-- navbar atas -->
    <div class="topnav"> 
      
      <!-- kotak kegiatan-->
      <div style="float: right;">
        <a href="{% url 'kegiatan:create_kegiatan' %}">Kegiatan</a>
      </div>  
      
      <!-- kotak matkul-->
      <div style="float: right;">
          <a href="{% url 'matkul:create_matkul' %}">Matkul</a>
      </div>

      <!-- kotak skill & swot  -->
      <div style="float: right;">
          <a href="{% url 'main:home' %}#section3" >Skill & SWOT</a>
      </div>

      <!-- kotak track record  -->
      <div style="float: right;">
          <a href="{% url 'main:home' %}#section2" >Track Record</a>
      </div>

      <!-- kotak intro -->
      <div style="float: right;">
          <a href="{% url 'main:home' %}#section1" >Intro</a>
      </div>
  </div>

  <!-- navbar bawah -->
  <div class="footer">
      <!-- button ig -->
      <div style="float: right;">
          <a href="https://www.instagram.com/ferdifdi/">
              <img src="{% static 'img/iglogo.png' %}" class="ikon">
          </a>
      </div>
      
      <!-- button linkedin  -->
      <div style="float: right;"> 
          <a href="https://www.linkedin.com/in/ferdifdi/">
              <img src="{% static 'img/linkedinlogo.png' %}" class="ikon">
          </a>
      </div>
  </div>    
</body>
  {% block content %}
  {% endblock content %}
</html>